---
# tasks file for 03_sudo_nopasswd

  - name: Allow sudo without password
    become: true
    lineinfile:
      path: /etc/sudoers
      line: '{{ ansible_user }} ALL=(ALL) NOPASSWD:ALL'
      validate: 'visudo -cf %s'
      backup: yes