---
- name: Configurar el escritorio
  hosts: local
  become: yes
  become_method: sudo

  vars:
    aur_packages:
      - visual-studio-code-bin
      - oh-my-zsh-git
      - oh-my-zsh-plugin-syntax-highlighting
      - oh-my-zsh-plugin-autosuggestions
      - ttf-meslo-nerd-font-powerlevel10k
      - microsoft-edge-stable-bin
    pacman_packages:
      - gnome
      - gdm
      - i3-wm
      - i3-gnome-flashback
      - alacritty
      - kitty
      - libreoffice
      - nitrogen
      - zsh
      - picom
      - i3status-rust
      - flatpak
      - zsh-theme-powerlevel10k
      - powerline-fonts
      - awesome-terminal-fonts
      - xss-lock
      - xorg-xev
    flatpak_packages:
      - com.spotify.Client
    lightdm_stuff:
      - eos-lightdm-slick-theme
      - lightdm-slick-greeter
      - lightdm

  tasks:
    - name: Allow sudo without password
      become: true
      lineinfile:
        path: /etc/sudoers
        line: '{{ ansible_user }} ALL=(ALL) NOPASSWD:ALL'
        validate: 'visudo -cf %s'
        backup: yes

    - name: Actualizar lista de paquetes disponibles
      community.general.pacman:
        update_cache: yes

    - name: Instalar paquetes de Pacman
      community.general.pacman:
        name: "{{ pacman_packages }}"
        state: latest

      
    - name: Instalar paquetes de AUR usando yay
      shell: >
        yay -S --needed --noconfirm {{ aur_packages | join(" ") }}
      become_user: "{{ ansible_user }}"
      when: ansible_os_family == "Archlinux"

    - name: Instalar paquetes de Flatpak
      become: yes
      become_user: "{{ ansible_user }}"
      flatpak:
        name: "{{ flatpak_packages }}"

    - name: Shell configuration
      shell: >
        cp /usr/share/oh-my-zsh/zshrc /home/"{{ ansible_user }}/.zshrc"
      become: yes
      become_user: "{{ ansible_user }}"
      
    - name: Change default shell to Zsh
      user:
        name: "{{ ansible_user }}"
        shell: /bin/zsh


    - name: Crear enlace simbólico para el tema de Zsh
      file:
        src: /usr/share/zsh-theme-powerlevel10k
        dest: /usr/share/oh-my-zsh/custom/themes/zsh-theme-powerlevel10k
        state: link

    - name: Configurar el archivo .zshrc con el tema y plugins
      lineinfile:
        path: /home/{{ ansible_user }}/.zshrc
        regex: '^ZSH_THEME='
        line: 'ZSH_THEME="zsh-theme-powerlevel10k/powerlevel10k"'
        state: present

    - name: Agregar plugins al archivo .zshrc
      lineinfile:
        path: /home/{{ ansible_user }}/.zshrc
        regex: '^plugins='
        line: |
          'plugins=(
          git 
          zsh-autosuggestions
          zsh-syntax-highlighting
          ssh-agent
          docker
          docker-compose
          gitfast)'
        state: present

    - name: Detener servicio de LightDM
      service:
        name: lightdm
        state: stopped

    - name: Deshabilitar servicio de LightDM
      service:
        name: lightdm
        enabled: no
    
    - name: Uninstall LightDM
      package:
        name: "{{ lightdm_stuff }}"
        state: absent

    - name: Habilitar servicio de GDM
      service:
        name: gdm
        enabled: yes

    - name: Reiniciar GDM
      service:
        name: gdm
        state: restarted

