---
- name: Desktop enviroment setup
  hosts: local
  become: yes
  become_method: sudo
  gather_facts: yes  # Enabling facts Gathering
  roles:
    - 01_set_facts
    - 02_remove_lightdm
    - 03_sudo_nopasswd
    - 04_software_install
    - 05_shell_setup
    - 06_window_manager_setup
    - 07_services_setup