---
# tasks file for 04_software_install

    - name: Update package list
      package:
        update_cache: yes

    - name: Print OS
      debug:
        msg: "Your system is: ==============>> {{ my_os }}" 
    
    
      # Archlinux specific installation

    - name: Install Software on Archlinux based distros
      include_tasks: 
        file: arch.yml
      when: my_os == "Archlinux"

      # Ubuntu/Debian based distros specific
    
    - name: Install Software on Ubuntu/Debian based distros
      include_tasks: 
        file: ubuntu-baseline.yaml
      when: my_os == "Ubuntu"
    
    - name: Install Docker on Ubuntu/Debian based distros
      include_tasks: 
        file: ubuntu-docker-task.yaml
      when: my_os == "Ubuntu"
    
    - name: Install Oh-My-zsh on Ubuntu/Debian based distros
      include_tasks: 
        file: ubuntu-oh-my-zsh-task.yaml
      when: my_os == "Ubuntu"
    
      # OS agnostic install/uninstall
    - name: Remove Packages
      become: true
      package:
        name: "{{ remove_packages }}"
        state: absent
      when: my_os == "Archlinux"

    