      - name: Apply Keyrings
        ansible.builtin.command: 
          cmd: install -m 0755 -d /etc/apt/keyrings
          creates: no
        when: my_os == "Ubuntu"

      
      - name: Adding Docker Repo Keys
        ansible.builtin.shell: 
          cmd: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
        when: my_os == "Ubuntu"
      
      - name: Setting Mode for Docker Keys
        ansible.builtin.command: 
          cmd: sudo chmod a+r /etc/apt/keyrings/docker.gpg
        when: my_os == "Ubuntu"
    
      - name: Adding Docker Repo to APT Sources
        ansible.builtin.shell: 
          cmd: | 
            echo \
              "deb [arch="$(dpkg --print-architecture)" signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
              "$(. /etc/os-release && echo "$VERSION_CODENAME")" stable" | \
              sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
        when: my_os == "Ubuntu"
      
      - name: Update APT again...
        apt:
          update_cache: yes
        when: my_os == "Ubuntu"

      - name: Installing Docker using APT
        apt:
          name: "{{ apt_docker_ubuntu }}"
          state: latest
        when: my_os == "Ubuntu"