- name: Install Oh-My-zsh globally 
  git:
    repo: "https://github.com/ohmyzsh/ohmyzsh"
    dest: "/usr/share/oh-my-zsh"
    version: master
    update: no

- name: Install Oh-My-zsh globally 
  git:
    repo: "https://github.com/romkatv/powerlevel10k.git"
    dest: "/usr/share/zsh-theme-powerlevel10k"
    version: master
    update: no
    depth: 1
  when: my_os == "Ubuntu"