---
# tasks file for 05_services_setup

    # GDM related operations
    - name: Enabling GDM Login Manager
      service:
        name: gdm
        enabled: yes

    # Docker related operations
    - name: Enabling Docker service
      service:
        name: gdm
        enabled: yes

    - name: Start Docker service
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: "Adding {{ ansible_user }} to Docker group"
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes

    - name: Restart Docker service
      systemd:
        name: docker
        state: restarted

    # Xorg Setup  
    - name: Xorg - Intel video setup
      template:
        src: files/xorg/xorg.conf.intel
        dest: /etc/X11/xorg.conf
        owner: root
        group: root
        mode: 0644

    # Reboot the system afterfwards
    - name: Reboot the system
      debug:
        msg: "You can now reboot the system"
